config/routes.rb
YpaIteration0::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }

  get "welcome/about"

  get "welcome/about"

  get "welcome/contact"

  get "login/login"

  get "login/logout"
  
  get "/events/search"

  get "/welcome/", to: 'welcome#index'

  get "/welcome/index", to: 'welcome#index'

  get "/users/list", to: 'users#list'

  get "/users/show/:id", to: 'users#show'

  post "/users/admin_reset_user_password" => "users#admin_reset_user_password"

  get "/reports/", to: 'events#reports'
  get "/reports/:past", to: 'events#reports'
  get "/reports/view/:id", to: 'events#report_view'

  get 'events/user', to: 'events#user'
  get 'events/rsvp/:id', to: 'events#rsvp'
  get 'events/check_in/:id', to: 'events#check_in'

  resources :categories

  resources :interests

  resources :events

  root :to => 'events#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def index
    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

app/views/welcome/index.html.erb
<% content_for :application do %>

    <tr>
      <!-- ============ NAVIGATION BAR SECTION ============== -->
      <td colspan="2" align="right" style="height: 20px;" bgcolor="#a9ae9f"><%= link_to(name="Login" , login_login_path) %></td>
    </tr>



<% end %>

<%= render template: "layouts/application" %>