config/routes.rb
YpaIteration0::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }

  get "welcome/about"

  get "welcome/about"

  get "welcome/contact"

  get "login/login"

  get "login/logout"
  
  get "/events/search"

  get "/welcome/", to: 'welcome#index'

  get "/welcome/index", to: 'welcome#index'

  get "/users/list", to: 'users#list'

  get "/users/show/:id", to: 'users#show'

  post "/users/admin_reset_user_password" => "users#admin_reset_user_password"

  get "/reports/", to: 'events#reports'
  get "/reports/:past", to: 'events#reports'
  get "/reports/view/:id", to: 'events#report_view'

  get 'events/user', to: 'events#user'
  get 'events/rsvp/:id', to: 'events#rsvp'
  get 'events/check_in/:id', to: 'events#check_in'

  resources :categories

  resources :interests

  resources :events

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  require 'time'
  require 'date'

  attr_accessible :event_id, :name, :desc, :from_date, :to_date, :from_time, :to_time, :venue, :category, :category_id, :min_before_start, :max_before_end, :created_by, :updated_by, :deleted
  
  # an event must have a category
  belongs_to :category
  
  # associate event with user through user_event table
  has_many :user_events
  has_many :users, through: :user_events
  
  # use event_id as the primary key and not the default generated id column
  self.primary_key = "event_id"
  
  # the username, password fields must be present
  validates :name, :from_date, :to_date, :from_time, :to_time, presence: true
  
  # user cannot sign-in to the event before 30mins of the start
  validates :min_before_start, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 90 }
  
  # user can sign-in till 30mins before end
  validates :max_before_end, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 90 }
  
  # all date validations
  validate :from_date_cannot_be_in_the_past, :to_date_cannot_be_in_the_past, :to_date_cannot_be_less_than_from_date, :to_time_cannot_be_less_than_from_time
 
  # Registering ActiveRecord Callbacks
  before_create do
	recalculcate_from_time_and_to_time()
  end

  before_update do
    recalculcate_from_time_and_to_time()
  end
  
  def recalculcate_from_time_and_to_time
  	# from_time should be added to from_date, to_time should be added to to_date
    
	if from_date.present?
		self.from_time = Time.mktime(from_date.year, from_date.month, from_date.day, self.from_time.hour, self.from_time.min)
	end
	
	if to_date.present?
		self.to_time = Time.mktime(to_date.year, to_date.month, to_date.day, self.to_time.hour, self.to_time.min)
	end
  end
  
  def from_date_cannot_be_in_the_past
    if from_date.present? && from_date < Date.today
      errors.add(:from_date, "can't be in the past")
    end
  end

  def to_date_cannot_be_in_the_past
    if to_date.present? && to_date < Date.today
      errors.add(:to_date, "can't be in the past")
    end
  end
  
  def to_date_cannot_be_less_than_from_date
    if to_date.present? && to_date < from_date
      errors.add(:to_date, "can't be less than From Date")
    end
  end
  
  def to_time_cannot_be_less_than_from_time
    if to_time.present? && to_time < from_time
      errors.add(:to_time, "can't be less than From Time")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  helper_method :sort_column, :sort_direction

  ############################################################
  # before_filters                                           #
  ############################################################
  before_filter :require_is_admin_true, only: [:new, :create, :edit, :destroy, :reports, :report_view]

  ############################################################
  # require_                                                 #
  ############################################################
  def require_is_admin_true
    unless @is_admin == true
      redirect_to events_path
    end
  end

  ############################################################
  # index                                                    #
  ############################################################
  def index

  # the search "filter" should be in its own function!
	@events = Event.order(sort_column + " " + sort_direction)
	#@events = Event.where(deleted: false)
	
	if params[:name]
		@events = @events.where("name LIKE ?", "%#{params[:name]}%")
	end
	
	if params[:category_id]
		@events = @events.where("category_id = ?", params[:category_id])
	end
	
	if params[:venue]
		@events = @events.where("venue LIKE ?", "%#{params[:venue]}%")
	end
	
	if params[:from_date]
      day = params[:from_date]["written_on(3i)"];
      
	  if day.length != 0
        if day.length < 2
          day = "0" + day
        end

        month = params[:from_date]["written_on(2i)"];
        if month.length < 2
          month = "0" + month
        end
        date_string = params[:from_date]["written_on(1i)"] + "-" + month + "-" + day;
        
		@events = @events.where("from_date >= ?", date_string)
      end
    end
	
	if params[:to_date]
      day = params[:to_date]["written_on(3i)"];
      
	  if day.length != 0
        if day.length < 2
          day = "0" + day
        end

        month = params[:to_date]["written_on(2i)"];
        if month.length < 2
          month = "0" + month
        end
        date_string = params[:to_date]["written_on(1i)"] + "-" + month + "-" + day;
        
		@events = @events.where("to_date <= ?", date_string)
      end
    end
	
	# limit records to 10 per page
    @events = @events.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @events }
    end
  end


  ############################################################
  # report                                                   #
  ############################################################
  def reports

    @past = params[:past]

    if @past == "past"
      @past = params[:past]
      @events =  Event.where(["to_date < ?", Date.today])
      #@events = Event.order(sort_column + " " + sort_direction)
    else
      @events = Event.order(sort_column + " " + sort_direction)
    end
    @events = @events.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html # reports.html.erb
    end
  end

  ############################################################
  # report_view                                              #
  ############################################################
  def report_view
    event_id = params[:id]
    @event =  Event.find(event_id)
    @count_rsvp =  UserEvent.where(['event_id = ? AND rsvp = ?', event_id, true]).count
    @count_check_in = UserEvent.where(['event_id = ? AND signin = ?', event_id, true]).count

    @users = User.select('users.first_name, users.last_name, users.email, users.phone, user_events.signin, user_events.rsvp').where(['user_events.event_id = ?', event_id]).joins(:user_events)


    respond_to do |format|
      format.html # report_view.html.erb
      format.json { render json: @events }
    end

  end



  ############################################################
  # user event's page, display events that user has rsvp     #
  # or has checked-in to                                     #
  ############################################################

  def user

    @events =  Event.joins(:user_events).where(['user_events.user_id = ? AND (user_events.rsvp = ? OR user_events.signin = ?) AND events.deleted = ? AND user_events.deleted = ?', @user_id, true, true, false, false]).paginate(page: params[:page], per_page: 10).order(sort_column + " " + sort_direction)

    render "events/user_event"
  end

  ############################################################
  # show                                                     #
  ############################################################
   def show

    @event =  Event.find(params[:id])

    @has_already_rsvp = has_user_rsvp?(params[:id])
    @already_checked_in = has_user_checked_in?(params[:id])
    @can_check_in = user_can_check_in?(params[:id])
    @user_can_rsvp = user_can_rsvp?(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  ############################################################
  # has_user_rsvp?                                           #
  ############################################################
  def has_user_rsvp?(event_id)
    db_row = UserEvent.select("rsvp").where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', params[:id], @user_id, false]).first
    if !db_row.nil? and db_row.rsvp == true
      true
    else
      false
    end
  end

  ############################################################
  # user_can_rsvp?                                           #
  ############################################################
  def user_can_rsvp?(event_id)
    event = Event.find(event_id)
    start_time = Time.local(event.from_date.strftime('%Y'), event.from_date.strftime('%m'), event.from_date.strftime('%d'), event.from_time.strftime('%H'), event.from_time.strftime('%M'))
    if start_time >= Time.now
      true
    else
      false
    end
  end

  ############################################################
  # can_user_check_in?                                       #
  ############################################################
  def user_can_check_in?(event_id)

    event =  Event.find(event_id)
    start_time = Time.local(event.from_date.strftime('%Y'), event.from_date.strftime('%m'), event.from_date.strftime('%d'), event.from_time.strftime('%H'), event.from_time.strftime('%M'))
    end_time = Time.local(event.to_date.strftime('%Y'), event.to_date.strftime('%m'), event.to_date.strftime('%d'), event.to_time.strftime('%H'), event.to_time.strftime('%M'))
    min_minutes_before = event.min_before_start
    max_minutes_after = event.max_before_end

    # db_row = UserEvent.select("signin").where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', params[:id], @user_id, false]).first

    if (TimeDifference.between(start_time, Time.now).in_minutes) <= min_minutes_before or
       (TimeDifference.between(Time.now, end_time).in_minutes) <= max_minutes_after or
       (start_time - Time.now) * (Time.now - end_time) >= 0
        db_row = UserEvent.select("signin").where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', event_id, @user_id, false]).first
      if !db_row.nil? and db_row.signin == true
        false
      else
        true
      end
    else
      false
    end
  end


  ############################################################
  # process click on check_in button on event show           #
  ############################################################
  def check_in

    event_id = params[:id]
    if user_can_check_in?(event_id)
      row = UserEvent.where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', event_id, @user_id, false]).first

      if row
        row.signin = true
      else
        row = new_user_event_obj(event_id)
        row.signin = true
      end

      row.save!
      flash[:notice] = "You have successfully checked in to this event."

    else
      flash[:notice] = "You cannot checkin to this event"
    end

    redirect_to '/events/' + params[:id]
  end

  ############################################################
  # has_user_checkedn?                                       #
  ############################################################

  def has_user_checked_in?(event_id)
    row = UserEvent.where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', event_id, @user_id, false]).first
    if !row.nil? and row.signin == true
      true
    else
      false
    end
  end

  ############################################################
  # process click on rsvp/de-rsvp button on event show       #
  ############################################################
  def rsvp

    event_id = params[:id]

    if user_can_rsvp?(event_id)

      row = UserEvent.where(['user_events.event_id = ? AND user_events.user_id = ? AND user_events.deleted = ?', event_id, @user_id, false]).first

      if row
        row.rsvp = !row.rsvp
      else
        row = new_user_event_obj(event_id)
        row.rsvp = true
      end

      row.save!

     if row.rsvp== true
       flash[:notice] = "You have successfully RSVP'D to this event."
     else
       flash[:notice] = "You have successfully UN-RSVP'D to this event."
     end

    else
      flash[:alert] = "You cannot create/edit a rsvp to/of a past event."
    end

    redirect_to '/events/' + params[:id]

  end

  def new_user_event_obj(event_id)
    row = UserEvent.new
    row.event_id = event_id
    row.user_id = @user_id
    return row
  end


  ############################################################
  # new                                                      #
  ############################################################
  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    respond_to do |format|

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Name' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc, 'Description' %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :from_date, 'From Date' %><br />
    <%= f.date_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date, 'To Date' %><br />
    <%= f.date_select :to_date %>
  </div>
  <div class="field">
    <%= f.label :from_time, 'From Time' %><br />
    <%= f.time_select :from_time %>
  </div>
  <div class="field">
    <%= f.label :to_time, 'To Time' %><br />
    <%= f.time_select :to_time %>
  </div>
  <div class="field">
    <%= f.label :venue, 'Venue' %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :category_id, 'Category' %><br />
    <%= collection_select(:event, :category_id, Category.all, :id, :name) %>
  </div>

  <div>
    <p>Check-in will be allowed throughout the duration of the event.  If you would like to allow check-in
    before the start time and/or before the end time, please specify the desired thresholds below:</p>
  </div>

  <div class="field">
    <%= f.label :min_before_start, 'Sign-In Starts (minutes before event starts)' %><br />
    <%= f.number_field :min_before_start, value: 30 %>
  </div>
  <div class="field">
    <%= f.label :max_before_end, 'Sign-In Ends (minutes before event ends)' %><br />
    <%= f.number_field :max_before_end, value: 30 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :home do %>
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

<% end %>
<%= render template: "layouts/home" %>

app/views/events/index.html.erb
<% content_for :home do %>

<h1>Search Events</h1>
<%= form_tag events_path, :method => 'get' do %>
<table cellspacing="2" cellpadding="2" border="1">

  <tr>
    <td>
          <%= label_tag :name %>
    </td>
    <td>
          <%= text_field_tag :name,  params[:name]%>
    </td>
    <td>
          <%= label_tag :category_id %>
    </td>
    <td>
          <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name), include_blank: true %>
    </td>
	<td>
          <%= label_tag :venue %>
    </td>
    <td>
          <%= text_field_tag :venue,  params[:venue]%>
    </td>
  </tr>
  <tr>
	<td>
		<%= label_tag :from_date %>
	</td>
	<td>
        <%= date_select(:from_date, "written_on", {:start_year => 2010, :end_year => Date.current.year + 2, :include_blank => true, :default => nil}) %>
	</td>
	<td>
        <%= label_tag :to_date %>
	</td>
	<td>
        <%= date_select(:to_date, "written_on", {:start_year => 2010, :end_year => Date.current.year + 2, :include_blank => true, :default => nil}) %>
	</td>
	<td colspan="2">
      &nbsp;
    </td
  </tr>
  <tr>
    <td colspan="6">
      <%= submit_tag 'Search', :name => nil %>
    </td>
  </tr>
</table>
<% end %>

<h1>Listing Events</h1>

<table class="pretty" cellspacing="2" cellpadding="2" border="1">
  <tr>
    <!--<th>Event</th>-->
    <th><%= sortable "name", Event %></th>
    <th>Description</th>
    <th><%= sortable "venue", "Venue" %></th>
    <th><%= sortable "categories.name", "Category" %></th>
    <th><%= sortable "from_date", "From" %></th>
    <th><%= sortable "to_date", "To" %></th>
    <th colspan="3">Actions</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.desc %></td>
    <td><%= event.venue %></td>
    <td><%= event.category.blank? ? '' : event.category.name %></td>
    <td><%= event.from_date.strftime('%d-%b-%Y') + ' ' + event.from_time.strftime('%I:%M %p') %></td>
	<td><%= event.to_date.strftime('%d-%b-%Y') + ' ' + event.to_time.strftime('%I:%M %p') %></td>
    <td><%= link_to 'Show', event %></td>
    <!-- only show Edit and Destroy event link if user == admin -->
    <% if @is_admin == true %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= will_paginate @events %>
<br />
<!-- only show new event link if user == admin -->
<% if @is_admin == true %>
<%= link_to 'New Event', new_event_path %>
<% end %>

<% end %>
<%= render template: "layouts/home" %>

app/views/events/new.html.erb
<% content_for :home do %>
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

<% end %>
<%= render template: "layouts/home" %>

app/views/events/report_view.html.erb
<% content_for :home do %>

    <h1>
      <%= @event.name %> <div style="color: red; font-weight: bold; font-size: small; display: inline;">REPORT</div>
    </h1>

    <table cellpadding="5" cellspacing="5" style="border:1px solid #333333">
      <tr>
      <td align="right"><strong>Total RSVPs:</strong></td>
      <td><%= @count_rsvp %></td>
      </tr>
      <tr>
        <td align="right"><strong>Total Checked-in:</strong></td>
        <td><%= @count_check_in%></td>
      </tr>
    </table>

    <table cellpadding="5" cellspacing="5">
        <tr>
          <th style="font-size:10pt;" align="left">Name</th>
          <th style="font-size:10pt;" align="left">Email</th>
          <th style="font-size:10pt;" align="left">Phone</th>
          <th style="font-size:10pt;" align="center">RSVP?</th>
          <th style="font-size:10pt;" align="center">Checked-in?</th>
        </tr>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.last_name %>, <%= user.first_name %></td>
            <td><%= user.email %></td>
            <td><%= user.phone %></td>
            <td align="center"><%= user.rsvp.upcase %></td>
            <td align="center"><%= user.signin.upcase %></td>
          </tr>
      <% end %>
    </table>


<% end %>
<%= render template: "layouts/home" %>

app/views/events/reports.html.erb
<% content_for :home do %>

    <h1>Reports</h1>

    <div style="padding-bottom:7px;">
    <% if @past == "past" %>
        <a href="/reports/">Show All Events</a>
    <% else %>
        <a href="/reports/past">Show Only Past Events</a>
    <% end %>
    </div>
    <table class="pretty" cellspacing="2" cellpadding="2" border="1">
      <tr>
        <th><%= sortable "name", Event %></th>
        <th>Venue</th>
        <th><%= sortable "from_date", "From" %></th>
        <th><%= sortable "to_date", "To" %></th>
        <th><%= sortable "categories.name", "Category" %></th>
        <th colspan="1">Actions</th>
      </tr>

      <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.venue %></td>
            <td><%= event.from_date.strftime('%d-%b-%Y') + ' ' + event.from_time.strftime('%I:%M %p') %></td>
            <td><%= event.to_date.strftime('%d-%b-%Y') + ' ' + event.to_time.strftime('%I:%M %p') %></td>
            <td><%= event.category.blank? ? '' : event.category.name %></td>
            <td><a href="/reports/view/<%=event.event_id%>">View</a></td>
          </tr>
      <% end %>

    </table>
    <%= will_paginate @events %>
    <br />

<% end %>
<%= render template: "layouts/home" %>

app/views/events/show.html.erb
<% content_for :home do %>

<h1>
  <%= @event.name %>
  <% if @has_already_rsvp %>
    <div style="color: red; font-weight: bold; font-size: small; display: inline;">RSVP'd</div>
  <% end %>
  <% if @already_checked_in and @has_already_rsvp %>
      <div style="font-weight: bold; font-size: small; display: inline;">|</div>
  <% end %>
  <% if @already_checked_in %>
      <div style="color: red; font-weight: bold; font-size: small; display: inline;">Checked-in</div>
  <% end %>
</h1>

<p>
  <b>Description:</b>
  <%= @event.desc %>
</p>

<p>
  <b>From:</b>
  <%= @event.from_date.strftime('%d-%b-%Y') + ' ' + @event.from_time.strftime('%I:%M %p') %>
</p>
<p>
  <b>To:</b>
  <%= @event.to_date.strftime('%d-%b-%Y') + ' ' + @event.to_time.strftime('%I:%M %p') %>
</p>
<p>
  <b>Venue:</b>
  <%= @event.venue %>
</p>

<p>
  <b>Category:</b>
  <%= @event.category.blank? ? '' : @event.category.name %>
</p>

<p>
  <b>Check-in starts:</b>
  <%= @event.min_before_start %> minutes before the event starts
</p>

<p>
  <b>Check-in ends:</b>
  <%= @event.max_before_end %> minutes before the event ends
</p>
<% if @user_can_rsvp %>
    <% if @has_already_rsvp %>
        <%= link_to 'UN-RSVP', '/events/rsvp/' + @event.id.to_s %>
    <% else %>
        <%= link_to 'RSVP', '/events/rsvp/' + @event.id.to_s %>
    <% end %>
<% end%>

<% if @can_check_in %>
 <%= link_to 'Check-in', '/events/check_in/' + @event.id.to_s %>
<% end %>
<!-- only show edit event link if user == admin -->
<div style="margin-top:15px;"><a href="/events/">Events</a> | <a href="/events/user">My Events</a>
<% if @is_admin == true %>
| <%= link_to 'Edit', edit_event_path(@event) %>
<% end %>
</div>

<% end %>
<%= render template: "layouts/home" %>

app/views/events/user_event.html.erb
<% content_for :home do %>

    <h1>My Events</h1>

    <table class="pretty" cellspacing="2" cellpadding="2" border="1">
      <tr>
        <th><%= sortable "name", Event %></th>
        <th>Description</th>
        <th><%= sortable "venue", "Venue" %></th>
        <th><%= sortable "categories.name", "Category" %></th>
        <th><%= sortable "from_date", "From" %></th>
        <th><%= sortable "to_date", "To" %></th>
        <!---- <th>Check-in Starts</th> ---->
        <!---- <th>Check-in Ends</th>  ---->
        <th colspan="1">Actions</th>
      </tr>

    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.desc %></td>
        <td><%= event.venue %></td>
        <td><%= event.category.blank? ? '' : event.category.name %></td>
        <td><%= event.from_date.strftime('%d-%b-%Y') + ' ' + event.from_time.strftime('%I:%M %p') %></td>
        <td><%= event.to_date.strftime('%d-%b-%Y') + ' ' + event.to_time.strftime('%I:%M %p') %></td>
        <!--- <td><%= event.min_before_start %></td> ---->
        <!--- <td><%= event.max_before_end %></td> ---->
        <td><%= link_to 'View', event %></td>
      </tr>
    <% end %>

    </table>
    <%= will_paginate @events %>
    <br />

<% end %>
<%= render template: "layouts/home" %>