config/routes.rb
YpaIteration0::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }

  get "welcome/about"

  get "welcome/about"

  get "welcome/contact"

  get "login/login"

  get "login/logout"
  
  get "/events/search"

  get "/welcome/", to: 'welcome#index'

  get "/welcome/index", to: 'welcome#index'

  get "/users/list", to: 'users#list'

  get "/users/show/:id", to: 'users#show'

  post "/users/admin_reset_user_password" => "users#admin_reset_user_password"

  get "/reports/", to: 'events#reports'
  get "/reports/:past", to: 'events#reports'
  get "/reports/view/:id", to: 'events#report_view'

  get 'events/user', to: 'events#user'
  get 'events/rsvp/:id', to: 'events#rsvp'
  get 'events/check_in/:id', to: 'events#check_in'

  resources :categories

  resources :interests

  resources :events

  root :to => 'events#index'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  attr_accessible :created_by, :deleted, :description, :updated_by
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @interests }
    end
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @interest = Interest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/new
  # GET /interests/new.json
  def new
    @interest = Interest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/1/edit
  def edit
    @interest = Interest.find(params[:id])
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(params[:interest])

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render json: @interest, status: :created, location: @interest }
      else
        format.html { render action: "new" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interests/1
  # PUT /interests/1.json
  def update
    @interest = Interest.find(params[:id])

    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_area :desciption %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <tr>
    <th>Desciption</th>
    <th>Created by</th>
    <th>Updated by</th>
    <th>Deleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interests.each do |interest| %>
  <tr>
    <td><%= interest.desciption %></td>
    <td><%= interest.created_by %></td>
    <td><%= interest.updated_by %></td>
    <td><%= interest.deleted %></td>
    <td><%= link_to 'Show', interest %></td>
    <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
    <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desciption:</b>
  <%= @interest.desciption %>
</p>

<p>
  <b>Created by:</b>
  <%= @interest.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%= @interest.updated_by %>
</p>

<p>
  <b>Deleted:</b>
  <%= @interest.deleted %>
</p>


<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>