config/routes.rb
YpaIteration0::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }

  get "welcome/about"

  get "welcome/about"

  get "welcome/contact"

  get "login/login"

  get "login/logout"
  
  get "/events/search"

  get "/welcome/", to: 'welcome#index'

  get "/welcome/index", to: 'welcome#index'

  get "/users/list", to: 'users#list'

  get "/users/show/:id", to: 'users#show'

  post "/users/admin_reset_user_password" => "users#admin_reset_user_password"

  get "/reports/", to: 'events#reports'
  get "/reports/:past", to: 'events#reports'
  get "/reports/view/:id", to: 'events#report_view'

  get 'events/user', to: 'events#user'
  get 'events/rsvp/:id', to: 'events#rsvp'
  get 'events/check_in/:id', to: 'events#check_in'

  resources :categories

  resources :interests

  resources :events

  root :to => 'events#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category_id, :name, :desc, :created_by, :updated_by, :deleted
  has_many :events
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Name' %><br />
    <%= f.text :name %>
  </div>
  <div class="field">
    <%= f.label :desc, 'Description' %><br />
    <%= f.text_area :desc %>
  </div>
  <!--
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  -->
  <!--
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </div>
  -->
  <!--
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table cellspacing="2" cellpadding="2" border="1">
  <tr>
	<th>Name</th>
    <th>Description</th>
    <!--<th>Created by</th>-->
    <!--<th>Updated by</th>-->
    <!--<th>Deleted</th>-->
    <th colspan="3">Actions</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
	<td><%= category.name %></td>
    <td><%= category.desc %></td>
    <!--<td><%= category.created_by %></td>-->
    <!--<td><%= category.updated_by %></td>-->
    <!--<td><%= category.deleted %></td>-->
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.desc %>
</p>

<!--
<p>
  <b>Created by:</b>
  <%= @category.created_by %>
</p>
-->

<!--
<p>
  <b>Updated by:</b>
  <%= @category.updated_by %>
</p>
-->

<!--
<p>
  <b>Deleted:</b>
  <%= @category.deleted %>
</p>
-->

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>